### ISSUE TITLE
Weird Error

### ISSUE THREAD

**Issue by dgramop** [hedii/php-crawler#10]
[PDOException]  
  SQLSTATE[HY000] [1049] Unknown database 'php-crawler' 

I created all the databases etc. There is the "php_crawler" database in mySQL. Error happens when I do

"php artisan crawler:build"

Thx!!

**Comment by hedii** [comment]
In .env file verify that the db name is php_crawler and not php-crawler

**Comment by dgramop** [comment]
Which ENV file? I can't find any such file... I feel kinda stupid, but
where is the ENV file?

On Sun, May 15, 2016 at 9:26 AM, hedii notifications@github.com wrote:

> In .env file verify that the db name is php_crawler and not php-crawler
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/hedii/php-crawler/issues/10#issuecomment-219285742

## 

Regards,

## Dhruv Gramopadhye

Controll Freak Operator and Everything
dGRAMOP Development
Penetration Testing | Animation and Rendering | Web Development | Mobile

## App Development | Embedded Electronics | and Misc Java Development.

http://socnet.16mb.com - My most recent and best project - still buggy,
still work in progress. Feel free to create an account
http://dgramop.co - An index page of my projects
http://m.freeplay.url.ph - A neat looking version of the latter link
http://freeplay.url.ph - An index page of random experiments.
http://ppn.hol.es - A currency system that is online that I use to "bribe"
other children. Over 1.5 years old, I already can name a bunch of security
flaws. Try ../ attack when creating an account.
http://m.ppn.hol.es - An even more neat looking version of the above,
scrolling only works on mobile browsers unless you really zoom in. The junk
text is there to enable scrolling.

**Comment by hedii** [comment]
It is at the root of this repo.

**Comment by dgramop** [comment]
Thanks.

On Mon, May 16, 2016 at 3:46 AM, hedii notifications@github.com wrote:

> It is at the root of this repo.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/hedii/php-crawler/issues/10#issuecomment-219368162

## 

Regards,

## Dhruv Gramopadhye

Controll Freak Operator and Everything
dGRAMOP Development
Penetration Testing | Animation and Rendering | Web Development | Mobile

## App Development | Embedded Electronics | and Misc Java Development.

http://socnet.16mb.com - My most recent and best project - still buggy,
still work in progress. Feel free to create an account
http://dgramop.co - An index page of my projects
http://m.freeplay.url.ph - A neat looking version of the latter link
http://freeplay.url.ph - An index page of random experiments.
http://ppn.hol.es - A currency system that is online that I use to "bribe"
other children. Over 1.5 years old, I already can name a bunch of security
flaws. Try ../ attack when creating an account.
http://m.ppn.hol.es - An even more neat looking version of the above,
scrolling only works on mobile browsers unless you really zoom in. The junk
text is there to enable scrolling.
