### ISSUE TITLE
Own logic

### ISSUE THREAD

**Issue by tpoxa** [hedii/php-crawler#11]
How can add own parse logic into crawler?
For example if I want to parse names also.

btw great tool!

**Comment by hedii** [comment]
The crawler uses a package i wrote called "Extractors" to extract resources from web pages (email and urls currently): https://github.com/hedii/extractors

You may find a way to extract names, write the logic and make a pull request to hedii/extractors.
When it's done i can help to implement the 'names' option on the crawler.
