### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by saranvarma** [hedii/php-crawler#12]
Even after 20 days of adding starting points still it is running but it didnt find atleast a single url or mail . please help me
![php crawler - mozilla firefox](https://cloud.githubusercontent.com/assets/14139476/15735346/a0c97820-28b5-11e6-8e3c-da44efbb457d.jpg)

**Comment by hedii** [comment]
Please paste here some pages where there is an email for each site

**Comment by saranvarma** [comment]
if i enter domain comakeit.com , it should fetch all emails from web related to comakeit.com like xxx@comakeit.com , yyy@comakeit.com like this . is it possible with this tool ?

**Comment by saranvarma** [comment]
check this screenshot . At bottom of the page , there is an email called 
![home - comakeit - mozilla firefox](https://cloud.githubusercontent.com/assets/14139476/15735741/9dd07ad0-28b8-11e6-8a6d-430e146823dd.jpg)
info@comakeit.com

**Comment by hedii** [comment]
Yes, and it is the only one one this website. I have just tested it and the email was found:

![capture d ecran 2016-06-02 a 08 28 34](https://cloud.githubusercontent.com/assets/5358048/15735863/23340e16-289c-11e6-8ade-74f29ec72bdd.png)

On what type of server are you running the package?
Please paste here the content of `storage/logs/laravel.log`

**Comment by saranvarma** [comment]
[2016-06-02 05:49:17] local.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:55
Stack trace:
#0 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(55): PDO->__construct('mysql:host=127....', 'root', 'root', Array)
#1 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Database\Connectors\MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=127....', Array, Array)
#2 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Database\Connectors\ConnectionFactory.php(61): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors{closure}()
#4 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Database\Connection.php(864): call_user_func(Object(Closure))
#5 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Database\Connection.php(732): Illuminate\Database\Connection->getPdo()
#6 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Database\Connection.php(621): Illuminate\Database\Connection->reconnectIfMissingConnection()
#7 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Database\Connection.php(342): Illuminate\Database\Connection->run('select \* from `...', Array, Object(Closure))
#8 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1461): Illuminate\Database\Connection->select('select * from`...', Array, true)
#9 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1447): Illuminate\Database\Query\Builder->runSelect()
#10 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(569): Illuminate\Database\Query\Builder->get(Array)
#11 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(303): Illuminate\Database\Eloquent\Builder->getModels(Array)
#12 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(273): Illuminate\Database\Eloquent\Builder->get(Array)
#13 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Auth\EloquentUserProvider.php(100): Illuminate\Database\Eloquent\Builder->first()
#14 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Auth\SessionGuard.php(353): Illuminate\Auth\EloquentUserProvider->retrieveByCredentials(Array)
#15 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Foundation\Auth\AuthenticatesUsers.php(74): Illuminate\Auth\SessionGuard->attempt(Array, false)
#16 [internal function]: App\Http\Controllers\Auth\AuthController->login(Object(Illuminate\Http\Request))
#17 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(78): call_user_func_array(Array, Array)
#18 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(146): Illuminate\Routing\Controller->callAction('login', Array)
#19 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(94): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\Auth\AuthController), Object(Illuminate\Routing\Route), 'login')
#20 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#21 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#22 D:\xampp\htdocs\php-crawler\app\Http\Middleware\RedirectIfAuthenticated.php(24): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#23 [internal function]: App\Http\Middleware\RedirectIfAuthenticated->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#25 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#26 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#28 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#29 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(96): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#30 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(54): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\Auth\AuthController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'login')
#31 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\Route.php(174): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\Http\Contro...', 'login')
#32 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\Route.php(140): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#33 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\Router.php(724): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\Routing\Router->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#35 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#36 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#37 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#39 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#40 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#41 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#42 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#44 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#45 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#46 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#47 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#49 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#50 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#51 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#52 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#54 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#55 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#56 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#57 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#59 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#60 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#61 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#62 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#63 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\Router.php(726): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#64 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\Router.php(699): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#65 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\Router.php(675): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#66 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(246): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#67 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http{closure}(Object(Illuminate\Http\Request))
#68 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#69 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#70 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#71 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#72 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#73 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#74 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#75 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#76 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#77 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#78 D:\xampp\htdocs\php-crawler\public\index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#79 {main}  
[2016-06-02 05:49:33] local.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000] [1049] Unknown database 'php_crawler'' in D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:55
Stack trace:
#0 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(55): PDO->__construct('mysql:host=127....', 'root', '', Array)
#1 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Database\Connectors\MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=127....', Array, Array)
#2 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Database\Connectors\ConnectionFactory.php(61): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors{closure}()
#4 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Database\Connection.php(864): call_user_func(Object(Closure))
#5 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Database\Connection.php(732): Illuminate\Database\Connection->getPdo()
#6 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Database\Connection.php(621): Illuminate\Database\Connection->reconnectIfMissingConnection()
#7 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Database\Connection.php(342): Illuminate\Database\Connection->run('select \* from `...', Array, Object(Closure))
#8 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1461): Illuminate\Database\Connection->select('select * from`...', Array, true)
#9 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1447): Illuminate\Database\Query\Builder->runSelect()
#10 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(569): Illuminate\Database\Query\Builder->get(Array)
#11 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(303): Illuminate\Database\Eloquent\Builder->getModels(Array)
#12 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(273): Illuminate\Database\Eloquent\Builder->get(Array)
#13 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Auth\EloquentUserProvider.php(100): Illuminate\Database\Eloquent\Builder->first()
#14 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Auth\SessionGuard.php(353): Illuminate\Auth\EloquentUserProvider->retrieveByCredentials(Array)
#15 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Foundation\Auth\AuthenticatesUsers.php(74): Illuminate\Auth\SessionGuard->attempt(Array, false)
#16 [internal function]: App\Http\Controllers\Auth\AuthController->login(Object(Illuminate\Http\Request))
#17 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(78): call_user_func_array(Array, Array)
#18 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(146): Illuminate\Routing\Controller->callAction('login', Array)
#19 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(94): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\Auth\AuthController), Object(Illuminate\Routing\Route), 'login')
#20 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#21 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#22 D:\xampp\htdocs\php-crawler\app\Http\Middleware\RedirectIfAuthenticated.php(24): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#23 [internal function]: App\Http\Middleware\RedirectIfAuthenticated->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#25 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#26 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#28 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#29 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(96): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#30 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(54): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\Auth\AuthController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'login')
#31 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\Route.php(174): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\Http\Contro...', 'login')
#32 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\Route.php(140): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#33 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\Router.php(724): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\Routing\Router->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#35 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#36 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#37 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#39 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#40 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#41 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#42 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#44 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#45 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#46 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#47 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#49 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#50 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#51 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#52 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#54 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#55 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#56 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#57 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#59 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#60 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#61 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#62 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#63 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\Router.php(726): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#64 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\Router.php(699): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#65 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\Router.php(675): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#66 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(246): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#67 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http{closure}(Object(Illuminate\Http\Request))
#68 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#69 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#70 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#71 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#72 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#73 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#74 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#75 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#76 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#77 D:\xampp\htdocs\php-crawler\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#78 D:\xampp\htdocs\php-crawler\public\index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#79 {main}

**Comment by saranvarma** [comment]
if i want to crawl entire web for emails of particlar domain , how to do it not only on particular website . Please see emailhunter.co you will get some idea

**Comment by hedii** [comment]
`Access denied for user 'root'@'localhost'`

You have not setup a database on your computer, or you have not modified the db credential in the .env file accordingly to your database. That is why it is not working.

**Comment by saranvarma** [comment]
after getting that error i have modified everything . that is the previous error not latest one

**Comment by hedii** [comment]
"if i want to crawl entire web for emails"
Lol, very bad idea and i will not implement that on the crawler.

`Unknown database 'php_crawler''`
This is the last error, do something about that

**Comment by saranvarma** [comment]
Changed that also bro all those are previous errors later i logged in , added searches also .

**Comment by saranvarma** [comment]
can you please give me some idea on how emailhunter.co crawls for emails ?

**Comment by hedii** [comment]
have you enable curl extension in xampp?

**Comment by saranvarma** [comment]
yes

**Comment by saranvarma** [comment]
Bro , can you please give me your skype id will discuss this on skype

**Comment by hedii** [comment]
no skype, i have no time to debug your personal installation of this repo.
it is surely an environment problem with xampp.
Try something like laravel homestead to install the crawler, and it will work.
https://laravel.com/docs/5.2/homestead

I close the issue, because it is not an issue related to the source code of the repo.
