### ISSUE TITLE
Problem crawl

### ISSUE THREAD

**Issue by descuderosanchez** [hedii/php-crawler#13]
Sorry but when i start any search, this not crawl anything. The search is loading ... and not look nothing.

**Comment by hedii** [comment]
hi,
What is the url you are trying to crawl?
On what type of server are you running the crawler?

**Comment by descuderosanchez** [comment]
Hi,
My server is CentOS 7, i crawl http://artdinamica.com, this have an email at footer.
I'm looking for a few hours why but I can not know why does not work.
I installed Node.js, and npm dependencies, but i not look the problem.
The public URL is: http://crawler.desarrollo.extremapp.com

I search logs at storage/logs but there aren't any log.
I change the Debug_mode to true but any error appear. The crawl continue loading but don't search anything.

**Comment by hedii** [comment]
and on your server logs, php logs, nginx/apache logs?

also, make sure you have:
PHP >= 5.5.9
OpenSSL PHP Extension
PDO PHP Extension
Mbstring PHP Extension
Tokenizer PHP Extension

**Comment by descuderosanchez** [comment]
Hi,
I have enabled all extensions, my php version is 5.6.22 FPM, i search at apache logs /var/log/httpd, and the hosting logs and nothing, i don't see anything...
I have this error when i make npm install:
npm WARN deprecated chalkline@0.0.4: No longer sponsored by CT - please visit http://niftylettuce.com for more info
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN prefer global coffee-script@1.10.0 should be installed with -g
npm WARN prefer global marked@0.3.5 should be installed with -g
npm WARN prefer global jshint@2.9.2 should be installed with -g
npm WARN prefer global leasot@1.3.2 should be installed with -g
npm WARN prefer global node-gyp@3.3.1 should be installed with -g

I installed three times but nothing.
I install at var/www/vhosts/mydomain/subdomain/ and then i make /php-crawler/public of public website...but nothing...

**Comment by descuderosanchez** [comment]
You can see all information here:
http://crawler.desarrollo.extremapp.com/version.php

**Comment by descuderosanchez** [comment]
Ok, solved, the PHP-Version of hosting is 5.6 but the default php version of server is 5.4, i upgrade version of server and all found now.
Thank you.
