### ISSUE TITLE
A search gives no result, it is running and running ...

### ISSUE THREAD

**Issue by Ericmuc** [hedii/php-crawler#15]
Hi, I installed the crawler, but it gives no results, it is running endless. What can I do?
Thanks, best regards
Eric

**Comment by hedii** [comment]
check the server requirements: https://github.com/hedii/php-crawler#server-requirements
check the chrome console output and find errors
check logs in /storage/logs and find errors
check files/folder permissions: https://laravel.com/docs/master#configuration

**Comment by Ericmuc** [comment]
check the server requirements: all fulfilled
check the chrome console output and find errors: I am finding no error
check logs in /storage/logs and find errors: I don't undestand the log entries, can someone help, log enclosed
check files/folder permissions: https://laravel.com/docs/master#configuration: writing access ok
[laravel.zip](https://github.com/hedii/php-crawler/files/343560/laravel.zip)

Can someone help? Thanks, best regards, Eric

**Comment by hedii** [comment]
In your logs:
1-
`exec() has been disabled for security reasons`
If your server cannot run exec() php function, the crawler will not work. Change your server.

2-
`file_put_contents(/www/htdocs/w0148e71/www/gabou.eu.suche/storage/framework/sessions/52b5ebc19d93da9a7439cdf52a59daefc821b943): failed to open stream: Permission denied`
You still have permissions issues on your storage directory. maybe you have fix it, it is at the middle of the log file

**Comment by Ericmuc** [comment]
ok, thanks, now I enabled the exec() on the hoster with htaccess and it works! Great!

**Comment by hedii** [comment]
👍
