### ISSUE TITLE
The start time is shown with "2 hours ago"

### ISSUE THREAD

**Issue by Ericmuc** [hedii/php-crawler#16]
The time zone is UTC, but with summer time = DST, what can I do?  I tried already with htaccess with php_value date.timezone 'Europe/Berlin', but this don't work.
Thanks, Eric

**Comment by hedii** [comment]
change UTC to Europe/Berlin there: https://github.com/hedii/php-crawler/blob/master/config/app.php#L55

**Comment by Ericmuc** [comment]
Thanks, it works!
