### ISSUE TITLE
not found anything

### ISSUE THREAD

**Issue by MGA-Coder** [hedii/php-crawler#18]
anything is blank page ?
![screenshot_20160914130852](https://cloud.githubusercontent.com/assets/16436457/18510088/8665bb38-7a7c-11e6-8ecf-9d12092a3869.png)

**Comment by hedii** [comment]
I cannot help if you don't provide debug :)

please check:
- server requirments to run this package: https://github.com/hedii/php-crawler#server-requirements
- errors in your browser js console
- laravel logs in storage/logs/ folder
- your server logs, mysql logs, php logs, etc...

**Comment by MGA-Coder** [comment]
the error in this paths for this files css/app.css, js/app.js
it's running now
 but not found any details ?
No Emails , No URLS ??
![screenshot_20160914133715](https://cloud.githubusercontent.com/assets/16436457/18510825/7a22cf38-7a80-11e6-8009-18f424e4072f.png)

**Comment by MGA-Coder** [comment]
i test it from localhost ?

**Comment by hedii** [comment]
as i said, please provide the informations from my previous post if you want me to help you
