### ISSUE TITLE
'php-crawler/public/searches' not found

### ISSUE THREAD

**Issue by qqqlllyyyy** [hedii/php-crawler#19]
I installed the package and the step 'php artisan crawler:build' seems to be okay:
![screen shot 2016-09-14 at 11 08 57 am](https://cloud.githubusercontent.com/assets/9327901/18524058/b786d46a-7a6b-11e6-9c66-3a7296923f1e.png)

But I could not find anything in the browser:
![screen shot 2016-09-14 at 11 10 00 am](https://cloud.githubusercontent.com/assets/9327901/18524085/d66ec360-7a6b-11e6-8e4b-26580a9ab161.png)

My php version is 7.0.10 and the required extensions are installed: http://yz.bxaf.com:8001/phpinfo.php

**Comment by hedii** [comment]
You have not configured your web server.

On the same folder as your picture above, run `php artisan tinker`  then type `public_path();`and hit enter. It gives you the public directory path.

You have to configure your apache server root directory with this path.
