### ISSUE TITLE
How stay over the same 1 domain ?

### ISSUE THREAD

**Issue by allado** [hedii/php-crawler#2]
How stay over the same 1 domain ?

**Comment by hedii** [comment]
it is not possible for the moment.
it would be added next.
pull requests are welcome

**Comment by jackmcdowell** [comment]
Hey Allado take a look at this other project I was working on that stays on the domain to see if you get any ideas. It is much less elegant then Hedii's project but it might give you some ideas for incorporating a "stay on domain" check-box or something like that: [domainEmailCrawler](https://github.com/jackmcdowell/domainEmailCrawler)

**Comment by hedii** [comment]
hi @allado and @jackmcdowell.
check the branch https://github.com/hedii/php-crawler/tree/feature-domain-specific
I think it works well, i will be happy to hear if it does :)

**Comment by allado** [comment]
Hi Jack ... you are the man  !

Thanks !!!

2015-09-13 16:50 GMT-03:00 hedii notifications@github.com:

**Comment by jackmcdowell** [comment]
Thanks @allado but it was @hedii who you should be thanking!

**Comment by hedii** [comment]
i close, tell me if you have any issues with the domain specific branch

**Comment by allado** [comment]
Hi

How modify regex  $pattern =   ?

In Crawler.php to find urls without domain start

/comercios/item1.html
/comercios/item1.html
/casas/item1.html
/casas/item2.html
/casas/item3.html
..etc

You can modify it to find urls /xxxxx/xxxx ?

In the source code of the webpage:

<a href="comercios/alquiler-de-carpas.html
<http://www.laguiadefunes.com.ar/comercios/alquiler-de-carpas.html>">Alquiler
de carpas</a>

Regards !

2015-10-10 12:13 GMT-03:00 hedii notifications@github.com:

**Comment by hedii** [comment]
Hi @allado 
I am working on a new version that will be able to do that.
It is not possible with the current version.
watch this repo to be updated when it will be released
