### ISSUE TITLE
search "running", but nothing happens, cant figure it out

### ISSUE THREAD

**Issue by tomthedude** [hedii/php-crawler#21]
Hello,
I installed everything properly, whwn i add a new search it says "runnig", but its is all the time 0% crawled and nothing really happens.
Went over the problems here, some people had them, tried to follow these advices, but nothing helped.
Here is my Log (ALL DB related problems has been fixed!

[laravel.txt](https://github.com/hedii/php-crawler/files/540596/laravel.txt)

**Comment by hedii** [comment]
please check:
- server requirments to run this package: https://github.com/hedii/php-crawler#server-requirements
- **errors in your browser js console**
- laravel logs in storage/logs/ folder => if you have new logs
- your server logs, mysql logs, php logs, etc...

And on what server/machine are you running it.

**Comment by hedii** [comment]
i have fixed a bug (https://github.com/hedii/php-crawler/commit/add05bc29546b31e876585f05cbbbafa2ca5044a), try to re install a fresh copy and tell me if it is ok now.

**Comment by tomthedude** [comment]
Hi there, 
checked all of those, seems fine, there was some other dude with similar problem here, you told him to do that as well, and it didnt help him either.
running XAMPP on windows
I will try to re-install it late today, and will come back to update.
thank you very much.
