### ISSUE TITLE
Assets not loading

### ISSUE THREAD

**Issue by pinceladasdaweb** [hedii/php-crawler#22]
I followed the project installation guide, but as you can see, CSS and JS are not loading:

![captura de tela 2016-11-17 as 15 09 33](https://cloud.githubusercontent.com/assets/814325/20399466/439d415c-acd8-11e6-8a45-f598a6b706cd.png)

**Comment by hedii** [comment]
Is is not just the assets, you have misconfigured your web server i think.
There should not be a 'public' segment in the url. on the readme: 

> Point your webserver to the public directory: php-crawler/public

Seeing your screenshot, your localhost domain is pointing to php-crawler's parent folder.
It should be pointing to php-crawler/public
