### ISSUE TITLE
Nothing Works

### ISSUE THREAD

**Issue by wiprich** [hedii/php-crawler#23]
After NPM Install and Artisan Build, the page get 404 Not Found.
You point to http://localhost/php-crawler/public/ and then he goes to
http://localhost/php-crawler/public/searches 
Returns Not Found

The requested URL /php-crawler/public/searches was not found on this server.
Apache/2.4.10 (Ubuntu) Server at localhost Port 80

NPM Log:

npm WARN engine postcss@5.2.5: wanted: {"node":">=0.12"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN engine less@2.7.1: wanted: {"node":">=0.12"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN optional dep failed, continuing fsevents@1.0.15
npm WARN engine normalize-url@1.8.0: wanted: {"node":">=4"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN deprecated chalkline@0.0.4: No longer sponsored by CT - please visit http://niftylettuce.com for more info
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN engine vendors@1.0.1: wanted: {"node":">=0.11.0"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine postcss@5.2.5: wanted: {"node":">=0.12"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN optional dep failed, continuing fsevents@1.0.15
npm WARN engine normalize-url@1.8.0: wanted: {"node":">=4"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine vendors@1.0.1: wanted: {"node":">=0.11.0"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN optional dep failed, continuing fsevents@1.0.15
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN engine hawk@3.1.3: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine pbkdf2@3.0.9: wanted: {"node":">=0.12"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine pbkdf2@3.0.9: wanted: {"node":">=0.12"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine request@2.79.0: wanted: {"node":">= 4"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine hawk@3.1.3: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine form-data@2.1.2: wanted: {"node":">= 0.12"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
\
> node-sass@3.13.0 install /var/www/html/php-crawler/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! Error: ENOENT, utime '/var/www/html/php-crawler/node_modules/laravel-elixir/node_modules/babel-preset-es2015/node_modules/babel-plugin-check-es2015-constants/node_modules/babel-runtime/node_modules/core-js/modules/es6.object.create.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.19.0-15-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /var/www/html/php-crawler
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! path /var/www/html/php-crawler/node_modules/laravel-elixir/node_modules/babel-preset-es2015/node_modules/babel-plugin-check-es2015-constants/node_modules/babel-runtime/node_modules/core-js/modules/es6.object.create.js
npm ERR! fstream_path /var/www/html/php-crawler/node_modules/laravel-elixir/node_modules/babel-preset-es2015/node_modules/babel-plugin-check-es2015-constants/node_modules/babel-runtime/node_modules/core-js/modules/es6.object.create.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call utimes
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:305:19
npm ERR! fstream_stack Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/var/www/html/php-crawler/node_modules/laravel-elixir/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-classes/node_modules/babel-runtime/node_modules/core-js/es6'
npm ERR! error rolling back  laravel-elixir@4.2.1 { [Error: ENOTEMPTY, rmdir '/var/www/html/php-crawler/node_modules/laravel-elixir/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-classes/node_modules/babel-runtime/node_modules/core-js/es6']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/var/www/html/php-crawler/node_modules/laravel-elixir/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-classes/node_modules/babel-runtime/node_modules/core-js/es6' }
npm ERR! node-sass@3.13.0 install: `node scripts/install.js`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the node-sass@3.13.0 install script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.19.0-15-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /var/www/html/php-crawler
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! Error: ENOENT, lstat '/var/www/html/php-crawler/node_modules/laravel-elixir/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-arrow-functions/node_modules/babel-runtime/node_modules/core-js/client/core.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.19.0-15-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /var/www/html/php-crawler
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! path /var/www/html/php-crawler/node_modules/laravel-elixir/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-arrow-functions/node_modules/babel-runtime/node_modules/core-js/client/core.js
npm ERR! fstream_path /var/www/html/php-crawler/node_modules/laravel-elixir/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-arrow-functions/node_modules/babel-runtime/node_modules/core-js/client/core.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! Error: ENOENT, lstat '/var/www/html/php-crawler/node_modules/laravel-elixir/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-sticky-regex/node_modules/babel-types/node_modules/lodash/lodash.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.19.0-15-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /var/www/html/php-crawler
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! path /var/www/html/php-crawler/node_modules/laravel-elixir/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-sticky-regex/node_modules/babel-types/node_modules/lodash/lodash.js
npm ERR! fstream_path /var/www/html/php-crawler/node_modules/laravel-elixir/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-sticky-regex/node_modules/babel-types/node_modules/lodash/lodash.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/var/www/html/php-crawler/node_modules/laravel-elixir/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-classes/node_modules/babel-helper-define-map/node_modules/lodash'
npm ERR! error rolling back  babel-preset-es2015@6.18.0 { [Error: ENOTEMPTY, rmdir '/var/www/html/php-crawler/node_modules/laravel-elixir/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-classes/node_modules/babel-helper-define-map/node_modules/lodash']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/var/www/html/php-crawler/node_modules/laravel-elixir/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-classes/node_modules/babel-helper-define-map/node_modules/lodash' }
npm ERR! Error: ENOENT, lstat '/var/www/html/php-crawler/node_modules/laravel-elixir/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-classes/node_modules/babel-runtime/node_modules/core-js/modules/es6.reflect.construct.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.19.0-15-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /var/www/html/php-crawler
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! path /var/www/html/php-crawler/node_modules/laravel-elixir/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-classes/node_modules/babel-runtime/node_modules/core-js/modules/es6.reflect.construct.js
npm ERR! fstream_path /var/www/html/php-crawler/node_modules/laravel-elixir/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-classes/node_modules/babel-runtime/node_modules/core-js/modules/es6.reflect.construct.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/html/php-crawler/npm-debug.log
npm ERR! not ok code 0
wiprich@ubuntu:/var/www/html/php-crawler$ php artisan crawler:build
Application key [62eJknp7jmFcIIh9ePYFAObSxAuVQUAS] set successfully.
Nothing to migrate.
Crawler app ready!

**Comment by hedii** [comment]
your domain http://localhost/php-crawler has to point to the directory /var/www/html/php-crawler/public as written in the readme of this repo.

**Comment by wiprich** [comment]
You please could explain for me. I bet i don't the only one who has this doubt.

I point to the domain. Still nothing

Apache file:

<VirtualHost *:80>
    # The ServerName directive sets the request scheme, hostname and port that
    # the server uses to identify itself. This is used when creating
    # redirection URLs. In the context of virtual hosts, the ServerName
    # specifies what hostname must appear in the request's Host: header to
    # match this virtual host. For the default virtual host (this file) this
    # value is not decisive as it is used as a last resort host regardless.
    # However, you must set it for any further virtual host explicitly.
    #ServerName www.example.com

```
ServerAdmin webmaster@localhost
DocumentRoot /var/www/html/php-crawler/public

# Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
# error, crit, alert, emerg.
# It is also possible to configure the loglevel for particular
# modules, e.g.
#LogLevel info ssl:warn

ErrorLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log combined

# For most configuration files from conf-available/, which are
# enabled or disabled at a global level, it is possible to
# include a line for only one particular virtual host. For example the
# following line enables the CGI configuration for this host only
# after it has been globally disabled with "a2disconf".
#Include conf-available/serve-cgi-bin.conf
```

</VirtualHost>

**Comment by hedii** [comment]
@wiprich sorry, i don't know enough apache to help you, i use nginx.
You would be able to find apache laravel configuration on google and use it on your webserver.
Or install something like laravel homestead.

**Comment by wiprich** [comment]
Ok, then put your nginx config example.

I point it to the root. Still Nothing happen. 

Has to be another config in another file who needs to change? Maybe on the .htaccess?

![screenshot from 2016-11-19 10 50 44](https://cloud.githubusercontent.com/assets/8609282/20455564/106ba656-ae46-11e6-9599-7561e71d3aac.png)

**Comment by hedii** [comment]
https://www.digitalocean.com/community/tutorials/how-to-install-laravel-with-an-nginx-web-server-on-ubuntu-14-04

**Comment by wiprich** [comment]
I needed to put the exactly address. Then works. 

http://localhost/index.php
but he redirect to: http://localhost/index.php/searches

Anyway. It works.

**Comment by hedii** [comment]
yep, putting index.php proves that your apache vhost conf is messed up :)
