### ISSUE TITLE
Not crawling anything

### ISSUE THREAD

**Issue by dubems** [hedii/php-crawler#26]
This software doesnt crawling anything for me

**Comment by hedii** [comment]
@dubems without application log, server log, or anything else that describes the issue on your machine, i don't see what we can do...

**Comment by MHassanSaqib** [comment]
Same here?

**Comment by MHassanSaqib** [comment]
How can we resolve it?

**Comment by hedii** [comment]
> How can we resolve it?

By providing backend and frontend error logs, screenshots, context, etc...
