### ISSUE TITLE
Start new search button is not showing

### ISSUE THREAD

**Issue by gustiwijayakusuma** [hedii/php-crawler#27]
The button for starting new search is not showing, can you please help me with this??

Thank you very much

**Comment by hedii** [comment]
Hi, you may have some errors in the chrome console, in the log file, a screenshot, etc...

i cannot help without any information

**Comment by gustiwijayakusuma** [comment]
Hi, 
It's only showing like this pict. There is no start new search button, so i cannot crawl any page.

![untitled](https://user-images.githubusercontent.com/30118672/28121445-bbe14408-674d-11e7-94a2-ff0950e28204.jpg)

Please help me with this. Thank you.

**Comment by hedii** [comment]
On your picture, the site url is localhost/php-crawler/public

It must be only localhost as explained in the readme (https://github.com/hedii/php-crawler#installation).

Check your vhost conf, or use something like laravel homestead (https://laravel.com/docs/master/homestead)

**Comment by gustiwijayakusuma** [comment]
Actually after i try to modify your code a bit, i found the problem is in : 

link href="{{ elixir('css/app.css') }}" rel="stylesheet" and
<script src="{{ elixir('js/app.js') }}"></script>

Elixir is not working.

Can you help me with this??

Thank you very much

**Comment by hedii** [comment]
try /css/app.css and /js/app.js instead of {{ elixir('css/app.css') }} and {{ elixir('js/app.js') }}
