### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by ej-dk** [hedii/php-crawler#28]
Hi ,

i've installed php-crawler on ubuntu. but when i try to access the webgui i get an 404 page not found. Could you please help me with this error?

<img width="423" alt="screen shot 2017-07-20 at 13 38 17" src="https://user-images.githubusercontent.com/1306199/28415767-6a35f96e-6d51-11e7-85de-2769e6d1b540.png">

<img width="513" alt="screen shot 2017-07-20 at 13 40 22" src="https://user-images.githubusercontent.com/1306199/28415789-85cd3c8c-6d51-11e7-80e9-04863ebe8102.png">

<img width="389" alt="screen shot 2017-07-20 at 13 44 44" src="https://user-images.githubusercontent.com/1306199/28415810-a03a5b4a-6d51-11e7-89b6-61f68228a7e8.png">

**Comment by hedii** [comment]
Follow this apache conf from laravel documentation: https://laravel.com/docs/5.4/installation#web-server-configuration
