### ISSUE TITLE
Crawler is empty

### ISSUE THREAD

**Issue by ghost** [hedii/php-crawler#30]
![crawl](https://user-images.githubusercontent.com/32371020/31679847-ab93451c-b372-11e7-82d4-6b32031dba19.png)

I putted the script on the server but I got a almost white page

- PHP Version => 5.6.31

Did not get any error's 
(Login and register works)

Running on vestacp 0.9.8-17

**Comment by hedii** [comment]
php logs, webserver logs, syslog, js errors? Some users are having issues with panel based installs (like cpanel). can you test it on your local machine?

**Comment by ghost** [comment]
```
[Mon Oct 16 18:26:04.284485 2017] [:error] [pid 28598] [client xxx:42634] PHP Warning:  require(/home/spider/web/spider.xxxx.nl/public_html/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php): failed to open stream: No such file or directory in /home/spider/web/spider.xxxx.nl/public_html/vendor/composer/autoload_real.php on line 66
[Mon Oct 16 18:26:04.284558 2017] [:error] [pid 28598] [client xxx:42634] PHP Fatal error:  require(): Failed opening required '/home/spider/web/spider.xxxx.nl/public_html/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php' (include_path='.:/usr/share/pear:/usr/share/php') in /home/spider/web/spider.xxxx.nl/public_html/vendor/composer/autoload_real.php on line 66

```

But when I open it now, I get the same page as above. But I cannot see any error's in the backoffice.
When I tried it to do it using composer. The .htaccess does not work (Installed lamp), on ubuntu.

**Comment by ghost** [comment]
`login:1 Slow network is detected. Fallback font will be used while loading: chrome-extension://niloccemoadcdkdjlinkgdfekeahmflj/app/fonts/ProximaNova-Reg-webfont.woff
login:1 Slow network is detected. Fallback font will be used while loading: chrome-extension://niloccemoadcdkdjlinkgdfekeahmflj/app/fonts/ProximaNova-Reg-webfont.ttf
login:1 Slow network is detected. Fallback font will be used while loading: chrome-extension://niloccemoadcdkdjlinkgdfekeahmflj/app/fonts/ProximaNova-Sbold-webfont.woff
login:1 Slow network is detected. Fallback font will be used while loading: chrome-extension://niloccemoadcdkdjlinkgdfekeahmflj/app/fonts/ProximaNova-Sbold-webfont.ttf
login:1 Slow network is detected. Fallback font will be used while loading: chrome-extension://niloccemoadcdkdjlinkgdfekeahmflj/app/fonts/ProximaNova-Bold-webfont.woff
login:1 Slow network is detected. Fallback font will be used while loading: chrome-extension://niloccemoadcdkdjlinkgdfekeahmflj/app/fonts/ProximaNova-Bold-webfont.ttf
2app-d41d8cd98f.css Failed to load resource: the server responded with a status of 404 (Not Found)
login:1 Slow network is detected. Fallback font will be used while loading: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/fonts/fontawesome-webfont.woff2?v=4.5.0
login:1 Slow network is detected. Fallback font will be used while loading: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/fonts/fontawesome-webfont.woff?v=4.5.0
login:1 Slow network is detected. Fallback font will be used while loading: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/fonts/fontawesome-webfont.ttf?v=4.5.0
login:1 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/lato/v14/eFRpvGLEW31oiexbYNx7Y_esZW2xOQ-xsNqO47m55DA.woff2
login:1 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/lato/v14/GtRkRNTnri0g82CjKnEB0Q.woff2
login:1 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/lato/v14/dPJ5r9gl3kK6ijoeP1IRsvY6323mHUZFJMgTvxaG2iE.woff2
login:1 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/lato/v14/EsvMC5un3kjyUhB9ZEPPwg.woff2
login:1 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/lato/v14/UyBMtLsHKBKXelqf4x7VRQ.woff2
login:1 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/lato/v14/1YwB1sO8YE1Lyjf12WNiUA.woff2
login:1 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/lato/v14/ObQr5XYcoH0WBoUxiaYK3_Y6323mHUZFJMgTvxaG2iE.woff2
login:1 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/lato/v14/H2DMvhDLycM56KNuAtbJYA.woff2
login:1 Slow network is detected. Fallback font will be used while loading: https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/fonts/glyphicons-halflings-regular.woff2
login:1 Slow network is detected. Fallback font will be used while loading: https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/fonts/glyphicons-halflings-regular.woff
login:1 Slow network is detected. Fallback font will be used while loading: https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/fonts/glyphicons-halflings-regular.ttf
app-036129abbd.js Failed to load resource: the server responded with a status of 404 (Not Found)
login:1 This page includes a password or credit card input in a non-secure context. A warning has been added to the URL bar. For more information, see https://goo.gl/zmWq3m.
app-036129abbd.js Failed to load resource: the server responded with a status of 404 (Not Found)
/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)
login:1 Slow network is detected. Fallback font will be used while loading: chrome-extension://niloccemoadcdkdjlinkgdfekeahmflj/app/fonts/ProximaNova-Reg-webfont.woff
login:1 Slow network is detected. Fallback font will be used while loading: chrome-extension://niloccemoadcdkdjlinkgdfekeahmflj/app/fonts/ProximaNova-Reg-webfont.ttf
login:1 Slow network is detected. Fallback font will be used while loading: chrome-extension://niloccemoadcdkdjlinkgdfekeahmflj/app/fonts/ProximaNova-Sbold-webfont.woff
login:1 Slow network is detected. Fallback font will be used while loading: chrome-extension://niloccemoadcdkdjlinkgdfekeahmflj/app/fonts/ProximaNova-Sbold-webfont.ttf
login:1 Slow network is detected. Fallback font will be used while loading: chrome-extension://niloccemoadcdkdjlinkgdfekeahmflj/app/fonts/ProximaNova-Bold-webfont.woff
login:1 Slow network is detected. Fallback font will be used while loading: chrome-extension://niloccemoadcdkdjlinkgdfekeahmflj/app/fonts/ProximaNova-Bold-webfont.ttf
login:1 Slow network is detected. Fallback font will be used while loading: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/fonts/fontawesome-webfont.woff?v=4.5.0
login:1 Slow network is detected. Fallback font will be used while loading: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/fonts/fontawesome-webfont.ttf?v=4.5.0
login:1 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/lato/v14/eFRpvGLEW31oiexbYNx7Y_esZW2xOQ-xsNqO47m55DA.woff2
login:1 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/lato/v14/GtRkRNTnri0g82CjKnEB0Q.woff2
login:1 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/lato/v14/dPJ5r9gl3kK6ijoeP1IRsvY6323mHUZFJMgTvxaG2iE.woff2
login:1 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/lato/v14/EsvMC5un3kjyUhB9ZEPPwg.woff2
login:1 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/lato/v14/UyBMtLsHKBKXelqf4x7VRQ.woff2
login:1 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/lato/v14/ObQr5XYcoH0WBoUxiaYK3_Y6323mHUZFJMgTvxaG2iE.woff2
login:1 Slow network is detected. Fallback font will be used while loading: https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/fonts/glyphicons-halflings-regular.woff2
login:1 Slow network is detected. Fallback font will be used while loading: https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/fonts/glyphicons-halflings-regular.woff
login:1 Slow network is detected. Fallback font will be used while loading: https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/fonts/glyphicons-halflings-regular.ttf
login:1 Slow network is detected. Fallback font will be used while loading: chrome-extension://niloccemoadcdkdjlinkgdfekeahmflj/app/fonts/ProximaNova-Reg-webfont.woff
login:1 Slow network is detected. Fallback font will be used while loading: chrome-extension://niloccemoadcdkdjlinkgdfekeahmflj/app/fonts/ProximaNova-Reg-webfont.ttf
login:1 Slow network is detected. Fallback font will be used while loading: chrome-extension://niloccemoadcdkdjlinkgdfekeahmflj/app/fonts/ProximaNova-Sbold-webfont.woff
login:1 Slow network is detected. Fallback font will be used while loading: chrome-extension://niloccemoadcdkdjlinkgdfekeahmflj/app/fonts/ProximaNova-Sbold-webfont.ttf
login:1 Slow network is detected. Fallback font will be used while loading: chrome-extension://niloccemoadcdkdjlinkgdfekeahmflj/app/fonts/ProximaNova-Bold-webfont.woff
login:1 Slow network is detected. Fallback font will be used while loading: chrome-extension://niloccemoadcdkdjlinkgdfekeahmflj/app/fonts/ProximaNova-Bold-webfont.ttf
login:1 Slow network is detected. Fallback font will be used while loading: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/fonts/fontawesome-webfont.woff?v=4.5.0
login:1 Slow network is detected. Fallback font will be used while loading: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/fonts/fontawesome-webfont.ttf?v=4.5.0
login:1 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/lato/v14/eFRpvGLEW31oiexbYNx7Y_esZW2xOQ-xsNqO47m55DA.woff2
login:1 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/lato/v14/GtRkRNTnri0g82CjKnEB0Q.woff2
login:1 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/lato/v14/dPJ5r9gl3kK6ijoeP1IRsvY6323mHUZFJMgTvxaG2iE.woff2
login:1 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/lato/v14/EsvMC5un3kjyUhB9ZEPPwg.woff2
login:1 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/lato/v14/UyBMtLsHKBKXelqf4x7VRQ.woff2
login:1 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/lato/v14/ObQr5XYcoH0WBoUxiaYK3_Y6323mHUZFJMgTvxaG2iE.woff2
login:1 Slow network is detected. Fallback font will be used while loading: https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/fonts/glyphicons-halflings-regular.woff2
login:1 Slow network is detected. Fallback font will be used while loading: https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/fonts/glyphicons-halflings-regular.woff
login:1 Slow network is detected. Fallback font will be used while loading: https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/fonts/glyphicons-halflings-regular.ttf
login:1 Slow network is detected. Fallback font will be used while loading: chrome-extension://niloccemoadcdkdjlinkgdfekeahmflj/app/fonts/ProximaNova-Reg-webfont.woff
login:1 Slow network is detected. Fallback font will be used while loading: chrome-extension://niloccemoadcdkdjlinkgdfekeahmflj/app/fonts/ProximaNova-Reg-webfont.ttf
login:1 Slow network is detected. Fallback font will be used while loading: chrome-extension://niloccemoadcdkdjlinkgdfekeahmflj/app/fonts/ProximaNova-Sbold-webfont.woff
login:1 Slow network is detected. Fallback font will be used while loading: chrome-extension://niloccemoadcdkdjlinkgdfekeahmflj/app/fonts/ProximaNova-Sbold-webfont.ttf
login:1 Slow network is detected. Fallback font will be used while loading: chrome-extension://niloccemoadcdkdjlinkgdfekeahmflj/app/fonts/ProximaNova-Bold-webfont.woff
login:1 Slow network is detected. Fallback font will be used while loading: chrome-extension://niloccemoadcdkdjlinkgdfekeahmflj/app/fonts/ProximaNova-Bold-webfont.ttf
login:1 Slow network is detected. Fallback font will be used while loading: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/fonts/fontawesome-webfont.woff?v=4.5.0
login:1 Slow network is detected. Fallback font will be used while loading: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/fonts/fontawesome-webfont.ttf?v=4.5.0
login:1 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/lato/v14/eFRpvGLEW31oiexbYNx7Y_esZW2xOQ-xsNqO47m55DA.woff2
login:1 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/lato/v14/GtRkRNTnri0g82CjKnEB0Q.woff2
login:1 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/lato/v14/dPJ5r9gl3kK6ijoeP1IRsvY6323mHUZFJMgTvxaG2iE.woff2
login:1 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/lato/v14/EsvMC5un3kjyUhB9ZEPPwg.woff2
login:1 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/lato/v14/UyBMtLsHKBKXelqf4x7VRQ.woff2
login:1 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/lato/v14/ObQr5XYcoH0WBoUxiaYK3_Y6323mHUZFJMgTvxaG2iE.woff2
login:1 Slow network is detected. Fallback font will be used while loading: https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/fonts/glyphicons-halflings-regular.woff2
login:1 Slow network is detected. Fallback font will be used while loading: https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/fonts/glyphicons-halflings-regular.woff
login:1 Slow network is detected. Fallback font will be used while loading: https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/fonts/glyphicons-halflings-regular.ttf
app-d41d8cd98f.css Failed to load resource: the server responded with a status of 404 (Not Found)`

Sitting in a dutch train, slow internet :(

**Comment by hedii** [comment]
take a picture of the page, with the url visible (chrome url bar), with chrome devtools inspector opened on the network tab (reload the page before taking the screenshot), with the js console visible
