### ISSUE TITLE
Update vue

### ISSUE THREAD

**Issue by simonschaufi** [hedii/php-crawler#32]
Hi!
Thank you so much for sharing your project!

I would love to extend it even further (I'm not interested in crawling for emails but for other things).
Therefor I would love to use the latest version of laravel 5.5 (I already managed to update it successfully! 🎉).
To make it work with the latest version of vue a lot of things need to be changed, so I tried to get it running with the given versions you provide in your `package.json`, so I tried to update all npm packages but then got stuck with this error:

```
Vue packages version mismatch:

- vue@1.0.28
- vue-template-compiler@2.5.11

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.
```

my package.json (adjustments from the latest laravel version to use webpack instead of gulp)
```
{
  "private": true,
  "scripts": {
    "dev": "npm run development",
    "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch-poll": "npm run watch -- --watch-poll",
    "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "prod": "npm run production",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "devDependencies": {
    "bootstrap-sass": "^3.3.7",
    "cross-env": "^5.1",
    "laravel-mix": "^1.0",
    "moment": "^2.12.0",
    "vue": "^1.0.17",
    "vue-resource": "^0.7.0"
  }
}
```

Would you be able to help me?

**Comment by hedii** [comment]
in your package.json, try:
````
{
  ...
  "vue": "^2.5.0",
  "vue-template-compiler": "^2.5.0"
  ...
}
````

And then try to catch breaking changes between vue1 and vue2. And submit a PR :)

**Comment by simonschaufi** [comment]
done. When I now compile the Vue templates, i get parsing errors because there are some breaking changes. I'm a total newbie in Vue. Could you help me with the errors?
In exchange I can provide a fully running laravel 5.5 version from the backend side ;)

**Comment by simonschaufi** [comment]
@hedii Could you help me with the errors?

**Comment by hedii** [comment]
@simonschaufi I released a brand new version. please give it a try.

**Comment by simonschaufi** [comment]
Wow, you have basically rewritten everything including tests 🎉 You are awesome!
