### ISSUE TITLE
API routes problem

### ISSUE THREAD

**Issue by simonschaufi** [hedii/php-crawler#35]
Hi!
I use your crawler for quite some time already and thought I already had a working version but now coming back to the project again with the latest release (2.1.0). I have the following problem.

I can register, sign in and click on the new search button but entering a url in the form and submitting it will give me the following error:

```
Request URL: http://crawler.test/api/v1/users//searches
Request Method: POST
Status Code: 404 Not Found
```

I have no idea where the double slashes are coming from because all other routes are correct.

The other thing i noticed is that on every request I also see in the browser debug panel the following error:

```
Request URL: http://crawler.test/api/v1/users/me
Request Method: GET
Status Code: 401 Unauthorized
```

Using homestead with php 7.2.

Do you have a glue where the problem could be? Of course I followed all the installation instructions.

**Comment by hedii** [comment]
@simonschaufi it should be fixed now. Sorry for the delay.

**Comment by webdev-pw** [comment]
Hey, i have the same errors in my new installation.
What could be the reason?
