### ISSUE TITLE
block list

### ISSUE THREAD

**Issue by bnkcrypt** [hedii/php-crawler#36]
Is there a way I can create a block list so it does not crawl those links if fund in page like facebook, instagram etc etc

**Comment by hedii** [comment]
No, at the moment you can only limit a search to a specific domain name, or use no limitation at all.

**Comment by bnkcrypt** [comment]
Here can i list to a specific domain ? where can i find some info or documentation on that pls .

**Comment by hedii** [comment]
It is just a checkbox when you create a search (Limited?, checked by default).

If it is checked, the crawler will only search on the same domain name you entered when creating a new search.
