### ISSUE TITLE
composer test end with error

### ISSUE THREAD

**Issue by ashishkpaul** [hedii/php-crawler#38]
hello sir, getting error on successfully installation 

ERRORS!
Tests: 54, Assertions: 0, Errors: 54.
Script vendor/bin/phpunit handling the test event returned with error code 2

**Comment by hedii** [comment]
Hi, i am closing this issue because there is no debug info or logs whatsoever. Can do nothing with "Script vendor/bin/phpunit handling the test event returned with error code 2".

You can open a new one if you can supply more info.
