### ISSUE TITLE
Can't get it to work properly

### ISSUE THREAD

**Issue by PauloChoupinaIPB** [hedii/php-crawler#39]
I do everything accordingly: 

BUT:
$ php artisan crawler:build

PHP Warning:  require(/var/www/html/crawler/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/html/crawler/artisan on line 18
PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/html/crawler/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/crawler/artisan:18
Stack trace:
#0 {main}
  thrown in /var/www/html/crawler/artisan on line 18

**Comment by PauloChoupinaIPB** [comment]
I deploy a vps, install lamp, install composer (tried composer2 aswell) do:

composer create-project hedii/php-crawler crawler

create a mysql use with priviledges and crete the crawler db
then edit the .env to enter the user and pass for the mysql login
edit the

APP_URL=http://crawler.localhost

to APP_URL=http://localhost/php-crawler/
do:

php artisan crawler:build


~but i get :
root@vultr:/var/www/html/crawler# php artisan crawler:build
PHP Warning:  require(/var/www/html/crawler/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/html/crawler/artisan on line 18
PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/html/crawler/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/crawler/artisan:18
Stack trace:
#0 {main}
  thrown in /var/www/html/crawler/artisan on line 18

And when i access: localhost/php-crawler/
i got a: Not Found

**Comment by PauloChoupinaIPB** [comment]
Everything goes fine until:

root@vultr:~/crawler# php artisan crawler:build

In PackageManifest.php line 122:

  Undefined index: name

**Comment by hedii** [comment]
> PHP Warning: require(/var/www/html/crawler/vendor/autoload.php): Failed to open stream: No such file or directory

it says it all. try running `composer install` beforehand.

If you find a bug or something that is not working, please open a new issue, but I am not going to help further with basic stuff like this after closing the issue. Sorry and good luck.
