### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by horridon** [hedii/php-crawler#6]
[root@unit237 html]# ls
php-crawler
[root@unit237 html]# composer create-project hedii/php-crawler php-crawler

  [InvalidArgumentException]
  Could not find package hedii/php-crawler with stability stable.

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

What am I doing wrong?

**Comment by hedii** [comment]
try this and let me know if it is ok:
`composer self-update && composer create-project hedii/php-crawler php-crawler`

The package has 'stability stable', maybe composer is trying to get an old version. I don't have this problem with an up to date composer.

**Comment by horridon** [comment]
This is the output:

`You are already using composer version 0a8528c5c7de43eca15237add666b4f8219aedc4.

  [InvalidArgumentException]
  Could not find package hedii/php-crawler with stability stable.

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

`

**Comment by hedii** [comment]
What is your php version?
The required version is ">=5.5.9" (same as laravel)

**Comment by horridon** [comment]
PHP 5.3.3 (cli) (built: Feb  9 2016 10:36:17)

I will update it asap.

**Comment by hedii** [comment]
yes, update it :)
